// Code generated by "script/generate_lookup.go"; DO NOT EDIT.
package hashpwd

func LookUp(line, pwd string) bool {
	switch len(pwd) {
	case 17:
		return pwd == /* MySQL */ line[0:17]
	case 32:
		return pwd == /* NTLMv1 */ line[17:49] ||
			pwd == /* MD5 */ line[49:81] ||
			pwd == /* MD5x2 */ line[81:113] ||
			pwd == /* MD5x3 */ line[113:145] ||
			pwd == /* SHA1MD5 */ line[145:177]
	case 40:
		return pwd == /* SHA1 */ line[177:217] ||
			pwd == /* SHA1x2 */ line[217:257] ||
			pwd == /* MD5SHA1 */ line[257:297]
	case 64:
		return pwd == /* SHA256 */ line[297:361] ||
			pwd == /* MD5SHA256 */ line[361:425]
	}
	return false
}
