mysql:
  host: 127.0.0.1
  user: virzz
  pass: virzz9999
  name: virzz_platform
  charset: utf8mb4
redis:
  host: 127.0.0.1
  port: 6379
  pass: ""
  db: 0
server:
  host: 127.0.0.1
  port: 9999
jwt:
  secret: secret_for_jwt
  expires: 3600
wechat:
  appid: ""
  secret: ""
  token: ""
  aeskey: ""
  wxdb: 0
qiniu:
  access: ""
  secret: ""
  bucket: ""
qq:
  appid: ""
  secret: ""
  token: ""
mail:
  user: ""
  stmp:
    host: ""
    port: 0
    pass: ""
  alidirect:
    region: ""
    access: ""
    secret: ""
