// Code generated by "stringer -type=MsgType"; DO NOT EDIT.

package ghext

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Init-1]
	_ = x[Feat-2]
	_ = x[Fix-3]
	_ = x[Docs-4]
	_ = x[Style-5]
	_ = x[Perf-6]
	_ = x[Refactor-7]
	_ = x[Test-8]
	_ = x[Build-9]
	_ = x[CI-10]
	_ = x[Chore-11]
	_ = x[Revert-12]
	_ = x[Release-13]
}

const _MsgType_name = "InitFeatFixDocsStylePerfRefactorTestBuildCIChoreRevertRelease"

var _MsgType_index = [...]uint8{0, 4, 8, 11, 15, 20, 24, 32, 36, 41, 43, 48, 54, 61}

func (i MsgType) String() string {
	i -= 1
	if i < 0 || i >= MsgType(len(_MsgType_index)-1) {
		return "MsgType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MsgType_name[_MsgType_index[i]:_MsgType_index[i+1]]
}
