name: GitHub Extension
on:
  push:
    tags:
      - "g*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "cmd/public/gh-mozhu/script.sh"
