name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          architecture: x64
          check-latest: true
          cache: true

      - name: Mod Tidy
        run: go mod tidy

      - name: Build virzz
        run: go build -v ./cli/virzz

      - name: Build platform
        run: go build -v ./cli/platform
