name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Mod Download
        run: go mod download

      - name: Build virzz
        run: go run ./cli/_compile -F -M virzz

      - name: Build platform
        run: go run ./cli/_compile -F -M platform

      - name: Build public
        run: go run ./cli/_compile -F -M public
